### ISSUE TITLE
Windows and Linux support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/electron-boilerplate#5]
PR => https://github.com/sindresorhus/electron-boilerplate/pull/4

Gonna wait until `electron-packager` resolves some of its issues:
- https://github.com/maxogden/electron-packager/issues/40
- https://github.com/maxogden/electron-packager/issues/35
- https://github.com/maxogden/electron-packager/issues/36
- https://github.com/maxogden/electron-packager/issues/37

**Comment by sindresorhus** [comment]
Seems like it's possible now with little config using the the `--all` flag: https://github.com/maxogden/electron-packager/commit/a157f716a572515a2d117a8bb51e9da3e34022d3

I'm busy right now, but PR welcome if you want to see this.

**Comment by martijnrondeel** [comment]
`electron-packager . --out=dist --app-version=$npm_package_version --prune --asar --overwrite --all` fails on my system (Windows 10) because of `$npm_package_version` ([related issue](https://github.com/electron-userland/electron-packager/issues/400)), `%npm_package_version%` works however. Should there be a note somewhere about this?
